export const COMMON_EXAM_TEMPLATES = [
  {
    key: 'civil-service',
    label: '国考（常见）',
    description: '蓝底 35×45mm · 30KB 内',
    colorKey: 'blue',
    sizeType: 'custom',
    sizeUnit: 'mm',
    width: 35,
    height: 45,
    compressionMode: 'limit',
    limitKb: 30,
  },
  {
    key: 'teacher',
    label: '教资（常见）',
    description: '白底一寸 · 200KB 内',
    colorKey: 'white',
    sizeType: 'preset',
    sizeKey: 'one-inch',
    compressionMode: 'limit',
    limitKb: 200,
  },
  {
    key: 'postgraduate',
    label: '考研（常见）',
    description: '一寸单色底 · 100KB 内',
    colorKey: 'blue',
    sizeType: 'preset',
    sizeKey: 'one-inch',
    compressionMode: 'limit',
    limitKb: 100,
  },
  {
    key: 'visa',
    label: '签证（常见）',
    description: '33×48mm · 白底',
    colorKey: 'white',
    sizeType: 'preset',
    sizeKey: 'visa',
    compressionMode: 'preset',
    compressionKey: 'balanced',
  },
];
